name: CI .NET + Tests + Reports

on:
  push:
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Run Unit Tests with Coverage
      run: dotnet test --collect:"XPlat Code Coverage"

    - name: Publish Test Results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: ./TestResults/

    - name: Report Generator
      run: dotnet tool install -g dotnet-reportgenerator-globaltool &&
           reportgenerator "-reports:**/coverage.cobertura.xml" "-targetdir:coverage"

    - name: Deploy coverage to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./coverage